### PR TITLE
You can now specify padding as left/right and top/bottom in addition.

### PR DESCRIPTION
**Pull request by DevinPentecost**
This will allow layouts that are not perfectly symmetrical, for instance to add branding/bonus stuff later.

For example, this Numpad has extra padding on top.

image

### CODE REVIEW

**Review by CurrentResident — COMMENTED** [review]
Thanks for the contribution!  Please see the comments below.

**Comment by CurrentResident** [comment]
I'm going ahead and merging the pull request into a new branch where I'll address comments and add a related thing or two I've been meaning to do for a while anyway.

Thanks again for the contribution.

By the way, I built a board from drawings generated by this script, with costar-only stab cutouts.  As I don't have any kerf params yet, the resulting costar cutouts needed a little grinding with a dremel.  Just a heads up.

**Comment by DevinPentecost** [comment]
Can you give more insight as to what you mean with the cutouts? I'm about to cut a faceplate soon and if I need to make adjustments I'd rather fix them before the cut :)

I'm new to Github Pull requests, what do you mean by the comments you'll address? I can't seem to find them... :/

**Comment by CurrentResident** [comment]
Sure thing!  I'm referring to the rectangular slots in the top plate where you'd mount the stabilizer brackets.  When my plate came back from the shop, the stabilizers were a super-tight fit... enough so that I was afraid that the stabilizer would need to be destroyed to get it back out.  So I widened the slots very slightly with a dremel, and it worked great.

image

In the latest BoardBuilder.py on master, see around line 256:

            elif self.stabs == 'costar':

                s = translate( [ -1.6, -7.75, 0 ] )(
                    square(size=[3.3, 14])
                    )

That's the square that defines the slot.  I'm not sure how much widening would be enough, or how much would be too much.  I tend to err on the side of too little because you can always remove more material by hand... not so easy to add it.  :) If it was me, depending on how much it would increase the cost of the overall job, I would consider combining multiple plates on one drawing - say one with the slot thickness at 3.3, another at 3.35, then another at 3.4, maybe even 3.5.  Whatever you try, please let me know what worked for you!

Yeah I'm kind of new to Pull Requests too.  I take it GitHub didn't send a review notification?  It's entirely possible that I just didn't capture my comments correctly...?  If you scroll up on this pull request page, you should see a section " CurrentResident started a review " with some stuff I logged.  It's mostly simple comments, and one that required a wall thickness logic change.  No worries!  It's all integrated into master with the adjustments now.

**Comment by DevinPentecost** [comment]
Awesome, thanks for the details.

The laser cutter I'm using tends to cut wide (probably a focus issue that
we're looking into), so I think I'll be okay. Plus I intend to use wood so
I only need some sandpaper to widen the hole. I might try multiple sizes if
I get a chance. I was mostly worried about drastic changes :)

Thanks

**Pull request merged**
